### ISSUE TITLE
京东多账号时，wskey和pin匹配错误。

### ISSUE THREAD

**Issue by fichenx** [lzwme/x-scripts-rules#1]
京东多账号，每次登陆京东时获取到的wskey写入环境变量时，经常会与错误的pin匹配。多个账号登陆一遍，基本上多数都错的。也没找到任何规律。

**Comment by renxia** [comment]
因为wskey的请求里没有pin，所以是缓存的，是会有这个问题。一个技巧是，顺序登陆不同账号，登陆后点一下农场或签到领京豆，然后返回首页再回来，切换下一个账号
